### ISSUE TITLE
power is null

### ISSUE THREAD

**Issue by nortoh** [nortoh/FactionsPlusPlus#3]
```
java.lang.NullPointerException: Cannot invoke "dansplugins.factionsystem.objects.domain.PowerRecord.decreasePower()" because "power" is null
    at dansplugins.factionsystem.data.PersistentData.decreasePowerForInactivePlayers(PersistentData.java:525)
    at dansplugins.factionsystem.utils.extended.Scheduler$3.run(Scheduler.java:76)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245)
    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197)
    at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013)
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mattwb65** [comment]
this won't happen with our version, this happened in MF because they stored player data and player stats separately. closing out.
